In [1]:
import numpy as np

In [2]:
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [3]:
# Put into (2, 3, 4) Shape
b = a.reshape((2,3,4))
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [7]:
print(b[0, 0, 1])
print(b[0, 1, 0])
print(b[1, 0, 0])
print(b.shape)

1
4
12
(2, 3, 4)


In [5]:
# Put b into fortran array
c = b.reshape((-1), order='F')
print(c)

[ 0 12  4 16  8 20  1 13  5 17  9 21  2 14  6 18 10 22  3 15  7 19 11 23]


In [6]:
# Put b in flatten array
d = b.reshape(-1)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [8]:
np.reshape(b, (b.shape[2], b.shape[1], b.shape[0]), order='F').flatten()

array([ 0, 12,  4, 16,  8, 20,  1, 13,  5, 17,  9, 21,  2, 14,  6, 18, 10,
       22,  3, 15,  7, 19, 11, 23])

In [11]:
np.reshape(b, (b.shape[0], b.shape[1], b.shape[2]), order='F')

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])