In [9]:
import numpy as np

In [10]:
a = np.arange(9).reshape((3, 3))
print('a = %s' % a)
print('a elementwise dot a = %s' %str(a*a))
print('a dot a = %s' % str(a@a))

a = [[0 1 2]
 [3 4 5]
 [6 7 8]]
a elementwise dot a = [[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
a dot a = [[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]


In [11]:
for ind, e in enumerate(a.reshape(-1)):
    print('ind = ', np.unravel_index(ind, (3, 3)))
    print('element value is ', e)

ind =  (0, 0)
element value is  0
ind =  (0, 1)
element value is  1
ind =  (0, 2)
element value is  2
ind =  (1, 0)
element value is  3
ind =  (1, 1)
element value is  4
ind =  (1, 2)
element value is  5
ind =  (2, 0)
element value is  6
ind =  (2, 1)
element value is  7
ind =  (2, 2)
element value is  8


In [12]:
b = np.arange(3)[np.newaxis, :] * np.arange(3)[:, np.newaxis]
print(b)

[[0 0 0]
 [0 1 2]
 [0 2 4]]
